# Generated by Django 5.2.17 on 2026-09-07 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('reminder_type', models.CharField(choices=[('medicine', 'Medicine'), ('water', 'Water'), ('meal', 'Meal'), ('appointment', 'Doctor Appointment'), ('activity', 'Daily Activity')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('reminder_time', models.TimeField()),
                ('reminder_date', models.DateField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='patients.patient')),
            ],
        ),
    ]
