# Generated by Django 5.2.17 on 2026-09-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=100)),
                ('score', models.IntegerField(default=0)),
                ('attempts', models.IntegerField(default=0)),
                ('accuracy', models.FloatField(default=0.0)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=20)),
                ('completion_time', models.FloatField(default=0.0)),
                ('played_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
