# Generated by Django 5.2.17 on 2026-09-09 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('is_shared', models.BooleanField(default=False)),
                ('consent_given', models.BooleanField(default=False)),
                ('consent_given_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='latest_location', to='patients.patient')),
            ],
        ),
    ]
